apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-ruby-app-deployment
  labels:
    app: minikube-ruby-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minikube-ruby-app
  template:
    metadata:
      labels:
        app: minikube-ruby-app
    spec:
      containers:
      - name: minikube-ruby-app
        image: agassner/minikube-ruby-app:latest
        ports:
        - containerPort: 8080